### ISSUE TITLE
Tord's private todo list

### ISSUE THREAD

**Issue by SunyataZero** [peoples-fund/peoples-fund#16]
- [ ] volunteer wp webmasters -- where? asking in #openhatch and other irc channels
- [ ] Automatic updates through github?
  https://www.google.se/search?client=ubuntu&channel=fs&q=wordpress+automatic+update+from+github&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=Ig_gV7bNB-jk8Aeb95rIDQ
- [ ] Verify that there is a way to distinguish between one-time donations and recurring payments. Maybe the description field is updated?
  ![selection_001](https://cloud.githubusercontent.com/assets/10245688/18670254/5250da9a-7f3f-11e6-9c52-52116a33d495.png)
  (Context: We may need to know this for tax purposes)

**Comment by SunyataZero** [comment]
# Previous Discussion with Frederik
- Donation plugins
  - wp simple pay lite for stripe
  - https://wordpress.org/plugins/stripe/
  - PMP - paid memberships pro https://wordpress.org/plugins/paid-memberships-pro/

## Questions
- do we want recurring donations, single donations, or both?
- can you explain: "We can handle most with an online form that generates a pdf, and then emails and excel."

[Essential]
Payments, payments, payments <--- 

[Essential]
one time donations <---

[low priority]
forums

option of paying a whole year at once?
[low priority]

user:
country

PBS??? (Danish payment service)
- limitiations are?

**Comment by SunyataZero** [comment]
payment gateway or plugin, what we need:
- recurring
- "membership" or some other way to know which user is currently paying a recurring fee
- ability to not have to pay anything and still be a member??
- integrates with stripe
- ability for users to vote by choosing answers to different questions

**Comment by SunyataZero** [comment]
**Admin guide: https://docs.civicrm.org/user/en/stable/introduction/components/**

Here are some ways that you can find out whether CiviCRM is right for your organisation:
-     read the book! (you might be doing that right now)
-     identify your organisation needs
-     talk to others who use CiviCRM
-     talk to a CiviCRM consultant
-     play with a demonstration site
-     install a test database

Sending links to Frederick:
- https://docs.civicrm.org/user/en/stable/introduction/real-world-examples/
- https://docs.civicrm.org/user/en/stable/getting-prepared/is-civicrm-for-you/
- https://docs.civicrm.org/user/en/stable/getting-prepared/identifying-your-needs/

> Implementation costs - Include a budget for implementation that contemplates:
> 
> ```
> discovery and project management
> data clean up, consolidation and migration
> system configuration
> post implementation training and documentation
> ```
> 
> Maintenance costs - Include a budget for ongoing maintenance that contemplates:
> 
> ```
> pro-active server maintenance
> incremental data backups
> operating system and software upgrades
> ongoing training
> ```

---

> External hosting
> 
> With internal expertise you could manage the install and configuration in-house, but host CiviCRM with an external provider. In this instance, we recommended you rent a VPS (Virtual Private Server) to ensure you have complete control of all packages and libraries (e.g. PHP, MySQL, etc), and are therefore able to configure it to your specific requirements.
> 
> Many shared hosts restrict the level of access you have, and may not support CiviCRM if you are unable to install the required pre-requisites. Shared hosts can also be prone to performance issues, as the hardware is shared between a group of customers with varying usage levels; if one customer's website suddenly receives a large spike in traffic, every website on that server could experience a lengthy outage.
> 
> Disadvantages aside, leasing space on a shared host is typically cheaper than a VPS, and both are subscription services on a monthly or annual basis (discounts may be available for longer leases.
> 
> We advise that you trial run any service for a short-term before committing to a longer period.

https://docs.civicrm.org/user/en/stable/getting-prepared/transitioning-to-civicrm/

> When you start out on a new CiviCRM project you should spend time thinking about:
> 
> ```
> the people who will be involved in the project
> what the business goals of using CiviCRM are
> how you will approach the initial development
> what ongoing support you will need
> the costs associated with hosting and your IT infrastructure
> training and documentation
> change management
> ```

---

> Managing a CiviCRM project will require a **major time investment** from people within your organisation, even if you employ an external consultant. **Organisations often underestimate the amount of time that will be required from their staff in implementing an IT project** - such as **training**, modifying existing processes and providing new or updated information to relevant people. **It's not something that can be tacked on to the end of an already busy schedule and this should be taken into consideration.**

---

> CiviCRM doesn't work well on poor hosting, and under-budgeting for hosting may lead to other problems.

**Comment by SunyataZero** [comment]
https://docs.civicrm.org/user/en/stable/getting-prepared/is-civicrm-for-you/

**Comment by SunyataZero** [comment]
WP installation instructions: https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+WordPress

**Comment by SunyataZero** [comment]
Helping out (costs): http://164a.com/about-us/

wordpress.stackexchange

Where can I find volunteers for maintaining or developing a WordPress site?

I'm volunteering for a new non-profit that has very limited resources and was wondering where we can find volunteers for helping with maintaining (and maybe developing) a WordPress website. For finding FOSS developers i know about places such as idealist, sourceforge and openhatch, but what is the best place to find volunteers that know WordPress? (Doesn't have to be programmers)

Respectfully, Tord

**Comment by SunyataZero** [comment]
Alternatives:
- https://www.wpcharitable.com/
- PMP
- More: http://alternativeto.net/software/civicrm/

**Comment by SunyataZero** [comment]
# Payment processors

## Research

Looking at money.stackexchange.com

http://money.stackexchange.com/questions/6923/what-are-cheap-ways-to-accept-small-amounts-of-money-micropayments-on-my-web-s

**Comment by SunyataZero** [comment]
http://webmasters.stackexchange.com/questions/17588/deliver-my-website-all-over-the-world-hosting

https://www.quora.com/What-is-the-exact-difference-between-CDN-cloud-hosting-for-a-website-Are-both-services-different-or-are-they-common-with-website-hosting

Considerations for world-wide access when choosing a hosting company?

I'm volunteering for a small non-profit with limited funds, and we are in the process of choosing a host for our new website. The thing is that people in developing countries need to have access to the website (as well as the rest of the world), preferrably without too much lag

What do we need to think of when chosing a hosting company? Should we choose cloud hosting? CDN? Other technologies?

Grateful for help and with kind regards, Tord

Reference: http://webmasters.stackexchange.com/questions/20838/how-to-find-web-hosting-that-meets-my-requirements

**Comment by SunyataZero** [comment]
Sent to CiviHosting support:

> What does activating SSL cost? (Without a certificate)
> 
> Are backups done for both database and files? (On our last web host we had to do this manually)
> 
> Can we get a server in Europe with ssh access? What do we do practically to get this when signing up?
> 
> I read this "We can register domain names for $10 a year with a hosting account purchase and $15 a year for names purchased separately.", does this mean that if we transfer our domain name from our previous web host it will cost $15/month? (I'm asking because i thought it would be cheaper to not get a new domain name and i want to make sure i understand everything)
> 
> Is it possible to upgrade later on from a standard to an extended account?
> 
> Kind Regards,
> Tord

**Comment by SunyataZero** [comment]
A user who is not logged in sees this:

# Search bar (no title)

# Recent comments

No comments available.

# Recent content

Front page nr 3
sunyata

Web Development and Design
sunyata

Management
sunyata

Who we are
sunyata

The People's Fund for Global Health and Development
sunyata

bex
sunyata

What We Do
sunyata

Mission, vision and values
sunyata

# Syndicate

Subscribe to Syndicate

# Main menu

```
Home
Home3
What We Do
Who we are
bex
```

# User login

Username *
Password *

```
Create new account
Request new password
```

# Who's new

```
sunyata
```

# Who's online

There is currently 1 user online.

```
sunyata
```

---

A user logged in as an admin sees this:

# Search bar (no title) (not available for non-logged in user)

# Recent comments (same for non-logged-in user)

No comments available.

# Recent content (same for non-logged-in user)

Front page nr 3
sunyata
edit    delete
Web Development and Design
sunyata
edit    delete
Management
sunyata
edit    delete
Who we are
sunyata
edit    delete
The People's Fund for Global Health and Development
sunyata
edit    delete
bex
sunyata
edit    delete
What We Do
sunyata
edit    delete
Mission, vision and values
sunyata
edit    delete
More

# Syndicate (same for non-logged-in user)

Subscribe to Syndicate

# Default shortcuts (not available for non-logged in user)

Add content

# Find content (not available for non-logged in user)

# Main menu (same for non-logged-in user)

Home
Home3
What We Do 
Who we are
bex

# Management (not available for non-logged in user)

Administration

# Navigation (not available for non-logged in user)

Add content
CiviCRM

# User menu (User login for non-logged-in user)

My account
Log out

# Who's new (same for non-logged-in user)

sunyata

# Who's online (same for non-logged-in user)

Configure
There is currently 1 user online.
sunyata
